import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import GoogleMapReact from "google-map-react";

const AnyReactComponent = ({ text }) => <div><img src="https://img.icons8.com/color/48/000000/marker--v1.png"/><span style={{background: "white"}}>{text}</span></div>;

const data = [
  {
    id: 1,
    title: "Property1",
    lat: "59.955413",
    lng: "30.52"
  },

  {
    id: 2,
    title: "Property2",
    lat: "59.855413",
    lng: "30.60"
  },

  {
    id: 1,
    title: "Property3",
    lat: "59.655413",
    lng: "30.23"
  },

  {
    id: 1,
    title: "Property4",
    lat: "59.955413",
    lng: "30.33"
  }
]

export default function Home() {
  const defaultProps = {
    center: {
      lat: 59.95,
      lng: 30.33,
    },
    zoom: 11,
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{width: "100%", height: "100vh"}}>
        <GoogleMapReact
          bootstrapURLKeys={{key: "" }}
          defaultCenter={defaultProps.center}
          defaultZoom={defaultProps.zoom}
        >
          {
            data.map((item, id) => {
              return(
                <AnyReactComponent lat={item.lat} lng={item.lng} text={item.title} />
              )
            })
          }
          {/* <AnyReactComponent lat={59.955413} lng={30.337844} text="My Marker" /> */}
        </GoogleMapReact>
      </div>
    </div>
  );
}
